### ISSUE TITLE
下载了好几次 Lib 下载不了，请问是什么情况呀

### ISSUE THREAD

**Issue by liuwen370494581** [dawangzai/FloatWindow#1]

**Comment by liuwen370494581** [comment]
就是整个项目下载过来了，但是lib不在项目了

**Comment by dawangzai** [comment]
> 就是整个项目下载过来了，但是lib不在项目了



> 就是整个项目下载过来了，但是lib不在项目了

我下载了一下，并没有你说的问题，你是咋下载的？

**Comment by liuwen370494581** [comment]
就是很正常的下载，我试过很多次了 每次下载完之后压缩文件就会报错 文件已经损坏

**Comment by liuwen370494581** [comment]
但是里面就是少了lib 其他又是完整的

**Comment by liuwen370494581** [comment]
楼主 能否把这个文件打包 发我邮箱呢 最近一直想研究这个 非常感谢  370494581@qq.com

**Comment by dawangzai** [comment]
> 楼主 能否把这个文件打包 发我邮箱呢 最近一直想研究这个 非常感谢 [370494581@qq.com](mailto:370494581@qq.com)

发你了
